# Generated by Django 4.0.2 on 2022-07-31 20:01

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('province', models.CharField(max_length=15)),
                ('town', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=15)),
                ('post_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfoPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_phone', models.CharField(max_length=11)),
                ('cell_phone', models.CharField(max_length=11)),
                ('fax', models.CharField(max_length=11)),
                ('work_phone', models.CharField(max_length=11)),
                ('cellular_phone', models.CharField(max_length=11)),
                ('health_care_proxy_phone', models.CharField(max_length=11)),
                ('emergency_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='DemoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('wom', 'زن'), ('man', 'مرد'), ('ukw', 'نامشخص')], max_length=3)),
                ('educate_rate', models.CharField(choices=[('illit', 'بی سواد'), ('elmnt', 'ابتدایی'), ('dplom', 'دیپلم'), ('tchnc', 'کاردانی'), ('exprt', 'کارشناسی'), ('Mstrs', 'کارشناسی ارشد'), ('Phd', 'دکتری')], max_length=5)),
                ('economic_situation', models.CharField(choices=[('low', 'ضعیف'), ('norm', 'متوسط'), ('good', 'خوب'), ('best', 'عالی')], max_length=4)),
                ('status_job', models.CharField(choices=[('1', 'موضوعیت ندارد'), ('2', 'بیکار'), ('3', 'کشاورز'), ('4', 'کارگر'), ('5', 'کارمند'), ('6', 'بازنشسته'), ('7', 'آزاد')], max_length=2)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(130)])),
                ('weight', models.DecimalField(decimal_places=1, max_digits=1, max_length=3, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(400)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(250)])),
                ('BMI', models.DecimalField(decimal_places=1, max_digits=1, max_length=3, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)])),
                ('pregnancy_status', models.BooleanField(default=False)),
                ('breast_feeding_status', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
            ],
        ),
    ]
