# Generated by Django 4.0.2 on 2022-08-01 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCRF', '0002_contactinfoaddress_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinfo',
            name='BMI',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=3, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=3, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
