# Generated by Django 4.0.2 on 2022-08-01 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCRF', '0003_alter_healthinfo_bmi_alter_healthinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinfo',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, max_length=4, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
